#!/usr/bin/env python3
import os
import sys
import threading

print("application install started")
# path
ini_path = r'/etc/gateway'
print("ini file path: %s" % ini_path)
exec_path = r'/usr/local/bin'
print("exec file path: %s" % exec_path)

local_path = os.path.dirname(os.path.abspath(__file__))
print("local path: %s" % local_path)
config_path = os.path.join(local_path, 'config')
epd_path = os.path.join(local_path, 'epd_service')
web_path = os.path.join(local_path, 'web')
serial_path = os.path.join(local_path, 'serial')
epd_exec_path = os.path.join(exec_path, 'epd')
web_exec_path = os.path.join(exec_path, 'web')
serial_exec_path = os.path.join(exec_path, 'serial')
print("epd path:%s" % epd_exec_path)
print("web path:%s" % web_exec_path)
print("serial_path:%s" % serial_exec_path)
back_up_path = r'/var/backup'

def backup():
    os.system("%s" % (os.path.join(exec_path, 'packet')))
    os.system("cp backup.tar.gz %s" % back_up_path)

def rollback():
    os.chdir(back_up_path)
    os.system("tar -xvf backup.tar.gz")
    os.system("%s" % os.path.join("backup", "install"))

try:
    backup()
    # 拷贝epd服务
    if os.path.exists(epd_exec_path):
        os.system("rm -r %s" % epd_exec_path)
    os.system("mkdir -p %s" % epd_exec_path)        # 创建目标文件夹
    os.system("cp %s %s -rf" % (epd_path, epd_exec_path))
    # 拷贝web服务
    if os.path.exists(web_exec_path):
        os.system("rm -r %s" % web_exec_path)
    os.system("mkdir -p %s" % web_exec_path)
    os.system("cp %s %s -rf" % (web_path, web_exec_path))
    # 拷贝serial服务
    if os.path.exists(serial_exec_path):
        os.system("rm -rf %s" % serial_exec_path)
    os.system("mkdir -p %s" % serial_exec_path)
    os.system("cp -rf %s %s" % (os.path.join(serial_path, "serial_apt"), serial_exec_path))
    # 拷贝ini文件
    if not os.path.exists(ini_path):
        os.system("mkdir -p %s" % ini_path)
        os.system("cp -rf %s %s" % (config_path, ini_path))
    else:
        ls = os.listdir(config_path)
        ls = set(ls)
        ld = os.listdir(ini_path)
        ld = set(ld)
        l = ls - ld
        for f in l:
            os.system("cp -rf %s %s" % (os.path.join(config_path, f), ini_path))
    # 保存安装文件
    os.system("cp install %s" % exec_path)
    os.system("cp packet %s" % exec_path)
except Exception as e:
    print("error: %s" % e.__str__())
    rollback()
    sys.exit(-1)

# 10秒之后重新启动
count = 10
def time_interval():
    global count
    count = count - 1
    print("reboot after %d ......" % count)
    if count:
        th = threading.Timer(1, time_interval)
        th.start()
    else:
        print("reboot now ......")
        os.system("reboot")

try:
    print("reboot after %d ......" % count)
    th = threading.Timer(1, time_interval)
    th.start()
except:
    print("reboot cancel ...")
sys.exit(0)
